package com.checku.core.mock;

import com.checku.core.user.domain.User;
import com.checku.core.user.infrastructure.UserRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class FakeUserRepository implements UserRepository {

    private Long autoGeneratedId = 0L;
    private final List<User> users = new ArrayList<>();

    @Override
    public User save(User user) {
        if (isNewUser(user)) {
            return createUser(user);
        } else {
            return updateUser(user);
        }
    }

    private boolean isNewUser(User user) {
        return user.getId() == null;
    }

    private User createUser(User user) {
        User newUser = User.builder()
                .id(++autoGeneratedId)
                .pushToken(user.getPushToken())
                .createdAt(user.getCreatedAt())
                .updatedAt(user.getUpdatedAt())
                .build();
        users.add(newUser);
        return newUser;
    }

    private User updateUser(User user) {
        users.removeIf(item -> Objects.equals(item.getId(), user.getId()));
        users.add(user);
        return user;
    }
}
